#!/usr/bin/env bats
#
# BATS Test Suite: DESTRUCTIVE-OPS
# Generated by CLI Testing Specialist
# Target CLI: cmdrun
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/cmdrun/target/release/cmdrun"
    BINARY_BASENAME="cmdrun"

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[destructive-ops] Subcommand 'remove' requires confirmation" {
    # Test ID: destructive-remove-001
    # Tags: confirmation, remove

    # Execute command
    run echo 'n' | cmdrun remove

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "confirm" ]] || [[ "$stderr" =~ "confirm" ]]
}

@test "[destructive-ops] Subcommand 'remove' accepts --yes flag" {
    # Test ID: destructive-remove-002
    # Tags: force, remove

    # Execute command
    run cmdrun remove --yes

    # Assert exit code
    [ "$status" -eq 0 ]
}

