#!/usr/bin/env bats
#
# BATS Test Suite: HELP
# Generated by CLI Testing Specialist
# Target CLI: cmdrun
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/cmdrun/target/release/cmdrun"
    BINARY_BASENAME="cmdrun"

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[help] Display help for subcommand 'run'" {
    # Test ID: help-001
    # Tags: subcommand-help, run

    # Execute command
    run cmdrun run --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'list'" {
    # Test ID: help-002
    # Tags: subcommand-help, list

    # Execute command
    run cmdrun list --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'init'" {
    # Test ID: help-003
    # Tags: subcommand-help, init

    # Execute command
    run cmdrun init --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'validate'" {
    # Test ID: help-004
    # Tags: subcommand-help, validate

    # Execute command
    run cmdrun validate --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'graph'" {
    # Test ID: help-005
    # Tags: subcommand-help, graph

    # Execute command
    run cmdrun graph --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'completion'" {
    # Test ID: help-006
    # Tags: subcommand-help, completion

    # Execute command
    run cmdrun completion --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'remove'" {
    # Test ID: help-007
    # Tags: subcommand-help, remove

    # Execute command
    run cmdrun remove --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'add'" {
    # Test ID: help-008
    # Tags: subcommand-help, add

    # Execute command
    run cmdrun add --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'open'" {
    # Test ID: help-009
    # Tags: subcommand-help, open

    # Execute command
    run cmdrun open --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'edit'" {
    # Test ID: help-010
    # Tags: subcommand-help, edit

    # Execute command
    run cmdrun edit --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'info'" {
    # Test ID: help-011
    # Tags: subcommand-help, info

    # Execute command
    run cmdrun info --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'search'" {
    # Test ID: help-012
    # Tags: subcommand-help, search

    # Execute command
    run cmdrun search --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'config'" {
    # Test ID: help-013
    # Tags: subcommand-help, config

    # Execute command
    run cmdrun config --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'watch'" {
    # Test ID: help-014
    # Tags: subcommand-help, watch

    # Execute command
    run cmdrun watch --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'env'" {
    # Test ID: help-015
    # Tags: subcommand-help, env

    # Execute command
    run cmdrun env --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'history'" {
    # Test ID: help-016
    # Tags: subcommand-help, history

    # Execute command
    run cmdrun history --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'retry'" {
    # Test ID: help-017
    # Tags: subcommand-help, retry

    # Execute command
    run cmdrun retry --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'template'" {
    # Test ID: help-018
    # Tags: subcommand-help, template

    # Execute command
    run cmdrun template --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

@test "[help] Display help for subcommand 'plugin'" {
    # Test ID: help-019
    # Tags: subcommand-help, plugin

    # Execute command
    run cmdrun plugin --help

    # Assert exit code
    [ "$status" -eq 0 ]

    # Additional assertions
    [[ "$output" =~ "Usage:" ]] || [[ "$stderr" =~ "Usage:" ]]
}

