#!/usr/bin/env bats
#
# BATS Test Suite: MULTI-SHELL
# Generated by CLI Testing Specialist
# Target CLI: cmdrun
#

# Setup function (runs before each test)
setup() {
    # Set CLI binary path
    CLI_BINARY="/Users/sanae.abe/projects/cmdrun/target/release/cmdrun"
    BINARY_BASENAME="cmdrun"

    # Create temporary directory for test artifacts
    TEST_TEMP_DIR="$(mktemp -d)"
    export TEST_TEMP_DIR

    # Set secure umask
    umask 077
}

# Teardown function (runs after each test)
teardown() {
    # Cleanup temporary directory
    if [[ -n "${TEST_TEMP_DIR:-}" ]] && [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

@test "[multi-shell] Run --help in bash" {
    # Test ID: multi-shell-bash
    # Tags: bash

    # Execute command
    run bash -c 'cmdrun --help'

    # Assert exit code
    [ "$status" -eq 0 ]
}

@test "[multi-shell] Run --help in zsh" {
    # Test ID: multi-shell-zsh
    # Tags: zsh

    # Execute command
    run zsh -c 'cmdrun --help'

    # Assert exit code
    [ "$status" -eq 0 ]
}

@test "[multi-shell] Run --help in sh" {
    # Test ID: multi-shell-sh
    # Tags: sh

    # Execute command
    run sh -c 'cmdrun --help'

    # Assert exit code
    [ "$status" -eq 0 ]
}

